version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
    ports:
      - '5432:5432'

  app:
    build: .
    environment:
      DATABASE_URL: 'postgresql://root:root@host.docker.internal:5432/todo'
      PORT: 3000
      JWT_SECRET: 'ratata'
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  postgres-data:
